name = "mulroy-recipes-sync-cf"
main = "src/index.ts"
compatibility_date = "2024-11-07"
compatibility_flags = [
  "enable_request_signal",
  "nodejs_compat"
]


[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO"]

[env.prod]
name = "mulroy-recipes-sync-cf"

[[env.prod.durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[env.prod.migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO"]

[env.preview]
name = "mulroy-recipes-sync-cf-preview"

[[env.preview.durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[env.preview.migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO"]

[env.dev]
name = "mulroy-recipes-sync-cf-dev"

[[env.dev.durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[env.dev.migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO"]
